version: '3'
services:
 app:
  image: app-with-metrics
  ports:
   - 8080:8080
  environment:
   - TZ=Europe/Moscow
 prometheus:
  image: prometheus
  ports:
   - 9090:9090
  depends_on:
   - app    
 grafana:
  image: grafana
  ports:
   - 3000:3000
  depends_on:
   - prometheus

